import { VariantSpecKey } from '../models/variant-spec-key.model';
import { v4 as uuidv4 } from 'uuid';

export const seedVariantSpecKeys = async () => {
  const keys = [
    // Engine Performance
    {
      key_id: uuidv4(),
      name: 'Engine Type',
      slug: 'engine-type',
      category: 'engine_performance',
      section: 'Engine & Transmission',
      data_type: 'string',
      aliases: ['engine', 'motor type', 'powertrain'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Displacement',
      slug: 'displacement',
      category: 'engine_performance',
      section: 'Engine & Transmission',
      data_type: 'string',
      unit: 'cc',
      aliases: ['engine capacity', 'cc'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Max Power',
      slug: 'max-power',
      category: 'engine_performance',
      section: 'Engine & Transmission',
      data_type: 'string',
      unit: 'bhp',
      aliases: ['power', 'motor power', 'horsepower'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Max Torque',
      slug: 'max-torque',
      category: 'engine_performance',
      section: 'Engine & Transmission',
      data_type: 'string',
      unit: 'Nm',
      aliases: ['torque'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Cylinders',
      slug: 'cylinders',
      category: 'engine_performance',
      section: 'Engine & Transmission',
      data_type: 'number',
      aliases: ['no of cylinders', 'cylinder count'],
      is_published: true,
      is_deleted: false,
    },

    // Mileage Range
    {
      key_id: uuidv4(),
      name: 'ARAI Mileage',
      slug: 'arai-mileage',
      category: 'mileage_range',
      section: 'Mileage',
      data_type: 'string',
      unit: 'kmpl',
      aliases: ['mileage', 'fuel efficiency', 'arai certified mileage'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'City Mileage',
      slug: 'city-mileage',
      category: 'mileage_range',
      section: 'Mileage',
      data_type: 'string',
      unit: 'kmpl',
      aliases: ['city fuel efficiency'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Fuel Tank Capacity',
      slug: 'fuel-tank-capacity',
      category: 'mileage_range',
      section: 'Mileage',
      data_type: 'string',
      unit: 'litres',
      aliases: ['tank capacity', 'fuel capacity'],
      is_published: true,
      is_deleted: false,
    },

    // Battery & Charging
    {
      key_id: uuidv4(),
      name: 'Battery Capacity',
      slug: 'battery-capacity',
      category: 'battery_charging',
      section: 'Battery & Charging',
      data_type: 'string',
      unit: 'kWh',
      aliases: ['battery', 'battery pack', 'battery size'],
      fuel_type_visibility: ['electric'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Charging Time DC',
      slug: 'charging-time-dc',
      category: 'battery_charging',
      section: 'Battery & Charging',
      data_type: 'string',
      aliases: ['dc charging time', 'fast charging time', 'charging time dc'],
      fuel_type_visibility: ['electric'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Charging Time AC',
      slug: 'charging-time-ac',
      category: 'battery_charging',
      section: 'Battery & Charging',
      data_type: 'string',
      aliases: ['ac charging time', 'home charging time', 'charging time ac'],
      fuel_type_visibility: ['electric'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Electric Range',
      slug: 'electric-range',
      category: 'battery_charging',
      section: 'Battery & Charging',
      data_type: 'string',
      unit: 'km',
      aliases: ['range', 'claimed range', 'arai range'],
      fuel_type_visibility: ['electric'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Motor Type',
      slug: 'motor-type',
      category: 'battery_charging',
      section: 'Battery & Charging',
      data_type: 'string',
      aliases: ['electric motor type'],
      fuel_type_visibility: ['electric'],
      is_published: true,
      is_deleted: false,
    },

    // Dimensions
    {
      key_id: uuidv4(),
      name: 'Length',
      slug: 'length',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'string',
      unit: 'mm',
      aliases: ['overall length'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Width',
      slug: 'width',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'string',
      unit: 'mm',
      aliases: ['overall width'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Height',
      slug: 'height',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'string',
      unit: 'mm',
      aliases: ['overall height'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Wheelbase',
      slug: 'wheelbase',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'string',
      unit: 'mm',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Ground Clearance',
      slug: 'ground-clearance',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'string',
      unit: 'mm',
      aliases: ['ground clearance'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Boot Space',
      slug: 'boot-space',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'string',
      unit: 'litres',
      aliases: ['boot capacity', 'trunk space'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Seating Capacity',
      slug: 'seating-capacity',
      category: 'dimensions_practicality',
      section: 'Dimensions',
      data_type: 'number',
      unit: 'seats',
      aliases: ['seats', 'passenger capacity'],
      is_published: true,
      is_deleted: false,
    },

    // Safety
    {
      key_id: uuidv4(),
      name: 'Airbags',
      slug: 'airbags',
      category: 'safety',
      section: 'Safety',
      data_type: 'number',
      unit: 'count',
      aliases: ['number of airbags', 'airbag count'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Safety Rating',
      slug: 'safety-rating',
      category: 'safety',
      section: 'Safety',
      data_type: 'string',
      aliases: ['global ncap safety rating', 'bharat ncap safety rating', 'ncap rating'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'ABS',
      slug: 'abs',
      category: 'safety',
      section: 'Safety',
      data_type: 'boolean',
      aliases: ['anti-lock braking system'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'EBD',
      slug: 'ebd',
      category: 'safety',
      section: 'Safety',
      data_type: 'boolean',
      aliases: ['electronic brakeforce distribution'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'ESP',
      slug: 'esp',
      category: 'safety',
      section: 'Safety',
      data_type: 'boolean',
      aliases: ['electronic stability program', 'esc'],
      is_published: true,
      is_deleted: false,
    },

    // Suspension & Steering
    {
      key_id: uuidv4(),
      name: 'Front Suspension',
      slug: 'front-suspension',
      category: 'suspension_steering_brakes',
      section: 'Suspension',
      data_type: 'string',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Rear Suspension',
      slug: 'rear-suspension',
      category: 'suspension_steering_brakes',
      section: 'Suspension',
      data_type: 'string',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Steering Type',
      slug: 'steering-type',
      category: 'suspension_steering_brakes',
      section: 'Steering',
      data_type: 'string',
      aliases: ['steering', 'power steering'],
      is_published: true,
      is_deleted: false,
    },

    // Tyres
    {
      key_id: uuidv4(),
      name: 'Tyre Type',
      slug: 'tyre-type',
      category: 'tyres_wheels',
      section: 'Tyres',
      data_type: 'string',
      aliases: ['tire type'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Tyre Size',
      slug: 'tyre-size',
      category: 'tyres_wheels',
      section: 'Tyres',
      data_type: 'string',
      aliases: ['tire size'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Alloy Wheels',
      slug: 'alloy-wheels',
      category: 'tyres_wheels',
      section: 'Wheels',
      data_type: 'boolean',
      aliases: ['alloy rims'],
      is_published: true,
      is_deleted: false,
    },

    // Comfort
    {
      key_id: uuidv4(),
      name: 'Climate Control',
      slug: 'climate-control',
      category: 'comfort_convenience',
      section: 'Comfort',
      data_type: 'string',
      aliases: ['ac', 'air conditioning'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Sunroof',
      slug: 'sunroof',
      category: 'comfort_convenience',
      section: 'Comfort',
      data_type: 'string',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },

    // Infotainment
    {
      key_id: uuidv4(),
      name: 'Touchscreen',
      slug: 'touchscreen',
      category: 'infotainment_connectivity',
      section: 'Infotainment',
      data_type: 'string',
      unit: 'inch',
      aliases: ['display size', 'screen size'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Android Auto',
      slug: 'android-auto',
      category: 'infotainment_connectivity',
      section: 'Infotainment',
      data_type: 'boolean',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Apple CarPlay',
      slug: 'apple-carplay',
      category: 'infotainment_connectivity',
      section: 'Infotainment',
      data_type: 'boolean',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Bluetooth',
      slug: 'bluetooth',
      category: 'infotainment_connectivity',
      section: 'Infotainment',
      data_type: 'boolean',
      aliases: [],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Speakers',
      slug: 'speakers',
      category: 'infotainment_connectivity',
      section: 'Infotainment',
      data_type: 'number',
      unit: 'count',
      aliases: ['speaker count'],
      is_published: true,
      is_deleted: false,
    },

    // Warranty
    {
      key_id: uuidv4(),
      name: 'Basic Warranty Years',
      slug: 'basic-warranty-years',
      category: 'warranty',
      section: 'Warranty',
      data_type: 'number',
      unit: 'years',
      aliases: ['warranty years'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Basic Warranty Km',
      slug: 'basic-warranty-km',
      category: 'warranty',
      section: 'Warranty',
      data_type: 'number',
      unit: 'km',
      aliases: ['warranty km'],
      is_published: true,
      is_deleted: false,
    },
    {
      key_id: uuidv4(),
      name: 'Battery Warranty Years',
      slug: 'battery-warranty-years',
      category: 'warranty',
      section: 'Warranty',
      data_type: 'number',
      unit: 'years',
      aliases: [],
      fuel_type_visibility: ['electric'],
      is_published: true,
      is_deleted: false,
    },
  ];

  for (const key of keys) {
    const existing = await VariantSpecKey.findOne({ slug: key.slug });
    if (!existing) {
      await VariantSpecKey.create(key);
      console.log(`Created spec key: ${key.name}`);
    }
  }

  console.log('Variant spec keys seeded successfully');
};
