-- =========================================================================
-- MySQL Migration Script for Table: Blogs
-- Generated for API-Car database structure (MySQL-compatible)
-- =========================================================================

CREATE TABLE IF NOT EXISTS `Blogs` (
        id INT AUTO_INCREMENT PRIMARY KEY,
        blog_id VARCHAR(100) NOT NULL UNIQUE,
        title VARCHAR(255) NOT NULL,
        slug VARCHAR(255) NOT NULL UNIQUE,
        excerpt VARCHAR(500) NOT NULL,
        content LONGTEXT NOT NULL,
        author_name VARCHAR(255) NULL,
        author_id VARCHAR(100) NULL,
        category VARCHAR(255) NOT NULL,
        tags JSON NULL,
        thumbnail JSON NULL,
        images JSON NULL,
        link VARCHAR(1000) NULL,
        is_published TINYINT(1) DEFAULT 0,
        is_deleted TINYINT(1) DEFAULT 0,
        is_featured TINYINT(1) DEFAULT 0,
        meta_title VARCHAR(255) NULL,
        meta_description VARCHAR(500) NULL,
        meta_keywords VARCHAR(1000) NULL,
        og_image VARCHAR(1000) NULL,
        canonical_url VARCHAR(1000) NULL,
        noindex TINYINT(1) DEFAULT 0,
        article_type VARCHAR(50) NULL,
        article_status VARCHAR(50) DEFAULT 'draft',
        article_intent VARCHAR(50) NULL,
        target_keyword VARCHAR(255) NULL,
        freshness_score INT DEFAULT 100,
        seo_health_score INT NULL,
        stale_flags JSON NULL,
        last_verified_at DATETIME NULL,
        internal_link_count INT DEFAULT 0,
        related_articles_count INT DEFAULT 0,
        connected_cars JSON NULL,
        connected_variants JSON NULL,
        connected_brands JSON NULL,
        connected_body_types JSON NULL,
        connected_fuel_types JSON NULL,
        connected_comparisons JSON NULL,
        connected_collections JSON NULL,
        createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
        updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
        KEY `IX_Blogs_AuthorId` (`author_id`),
        KEY `IX_Blogs_Category` (`category`),
        KEY `IX_Blogs_IsPublished_IsDeleted` (`is_published`, `is_deleted`),
        KEY `IX_Blogs_IsFeatured` (`is_featured`)
);
