import { Router } from 'express';
import dashboardRoutes from '../../modules/dashboard/routes/dashboard.routes';
import auditRoutes from '../../modules/audit/routes/audit.routes';
import contentHealthRoutes from '../../modules/content-health/routes/content-health.routes';
import seoCollectionRoutes from '../../modules/seo-collections/routes/seo-collections.routes';
import fuelTypesIntelligenceRoutes from '../../modules/fuel-types-intelligence/routes/fuel-types-intelligence.routes';
import rankingsRoutes from '../../modules/rankings/routes/rankings.routes';
import authRoutes from '../../modules/auth/routes/auth.routes';
import comparisonRoutes from '../../modules/comparison/routes/comparison.routes';
import deletionWorkflowRoutes from '../../modules/deletion-workflow/routes/deletion-workflow.routes';
import discoveryRoutes from '../../modules/discovery/routes/discovery.routes';
import seoPresetRoutes from '../../modules/discovery/routes/seo-preset.routes';
import blogRoutes from '../../modules/blogs/routes/blog.routes';
import bodyTypeRoutes from '../../modules/bodyTypes/routes/bodyType.routes';
import brandRoutes from '../../modules/brands/routes/brand.routes';
import carRoutes, { adminCarRouter } from '../../modules/cars/routes/car.routes';
import variantRoutes from '../../modules/cars/routes/variant.routes';
import cityRoutes from '../../modules/cities/routes/city.routes';
import faqRoutes from '../../modules/faqs/routes/faq.routes';
import fuelTypeRoutes from '../../modules/fuelTypes/routes/fuel-type.routes';
import carImageRoutes from '../../modules/images/routes/car-image.routes';
import imageCategoryRoutes from '../../modules/images/routes/image-category.routes';
import imageSubcategoryRoutes from '../../modules/images/routes/image-subcategory.routes';
import imageRoutes from '../../modules/images/routes/image.routes';
import importRoutes from '../../modules/imports/routes/import.routes';
import intelligenceRoutes from '../../modules/intelligence/routes/intelligence.routes';
import redirectRoutes from '../../modules/redirects/routes/redirect.routes';
import settingsRoutes from '../../modules/settings/routes/settings.routes';
import taxonomyRoutes from '../../modules/taxonomy/routes/taxonomy.routes';
import userRoutes from '../../modules/users/routes/user.routes';
import governanceRoutes from '../../modules/governance/routes/governance.routes';
import popularCollectionsRoutes from '../../modules/popular-collections/routes/popular-collections.routes';
import lifecycleGovernanceRoutes from '../../modules/lifecycle-governance/routes/lifecycle-governance.routes';
import variantIngestionRoutes from '../../modules/variant-ingestion/routes/import-staging.routes';
import masterDataRoutes from '../../modules/master-data/routes/master-data.routes';
import masterDataPublicRoutes from '../../modules/master-data/routes/master-data-public.routes';
import adminChatbotRoutes from '../../modules/admin-chatbot/routes/adminChatbot.routes';

const router = Router();

router.use('/dashboard', dashboardRoutes);
router.use('/auth', authRoutes);
router.use('/cars', carRoutes);

// Admin namespace - mount admin car routes at /admin/cars for admin endpoints
// This provides backward compatibility for /admin/cars/{id} path while preserving /cars/admin/{id}
router.use('/admin/cars', adminCarRouter);
router.use('/variants', variantRoutes);
router.use('/brands', brandRoutes);
router.use('/body-types', bodyTypeRoutes);
router.use('/fuel-types', fuelTypeRoutes);
router.use('/blogs', blogRoutes);
router.use('/cities', cityRoutes);
router.use('/faqs', faqRoutes);
router.use('/images', imageRoutes);
router.use('/car-images', carImageRoutes);
router.use('/image-categories', imageCategoryRoutes);
router.use('/image-subcategories', imageSubcategoryRoutes);
router.use('/imports', importRoutes);
router.use('/users', userRoutes);
router.use('/settings', settingsRoutes);
router.use('/taxonomy', taxonomyRoutes);
router.use('/intelligence', intelligenceRoutes);
router.use('/audit', auditRoutes);
router.use('/deletion-requests', deletionWorkflowRoutes);
router.use('/redirects', redirectRoutes);
router.use('/comparisons', comparisonRoutes);
router.use('/discover', discoveryRoutes);
router.use('/discovery', discoveryRoutes); // Alias for /discover
router.use('/seo-presets', seoPresetRoutes);
router.use('/content-health', contentHealthRoutes);
router.use('/seo-collections', seoCollectionRoutes);
router.use('/fuel-types-intelligence', fuelTypesIntelligenceRoutes);
router.use('/rankings', rankingsRoutes);
router.use('/governance', governanceRoutes);
router.use('/popular-collections', popularCollectionsRoutes);
router.use('/admin/imports', variantIngestionRoutes);
router.use('/lifecycle-governance', lifecycleGovernanceRoutes);
router.use('/master-data/admin', masterDataRoutes);
router.use('/master-data/public', masterDataPublicRoutes);
router.use('/chatbot', adminChatbotRoutes);

export default router;
